### ISSUE TITLE
Lag format for rapid melding

### ISSUE THREAD

**Issue by chriswk** [navikt/nada-devrapid#4]

**Comment by chriswk** [comment]
Format Forslag:

type melding: string
tid-sent: epoch milli
team: string
data: map<string, string>
...

**Comment by mortenlj** [comment]
Selv om det er fristende å ha en sikkerhetsventil i form av et <string, string> map, så blir det så fort til at man bare får en stringly typed event, hvor selve skjemaet blir definert i kode rundt omkring.

Samtidig er det fryktelig vanskelig å forutsi alt man kunne finne på å trenge, men jeg tror vi med fordel kan prøve å bryte det litt mer ned i konkrete felter.

**Comment by mortenlj** [comment]
Eksempel på en DeploymentEvent fra Adevintas Devhose:
https://github.com/fiaas/fiaas-deploy-daemon/blob/master/fiaas_deploy_daemon/usage_reporting/transformer.py#L65**

|| Feltnavn || Beskrivelse ||
| id | Unik ID for deployment |
| application | Navn på applikasjon |
| environment | Kjøremiljø |
| repository | Github repo |
| started_at | Timestamp for når deployment startet |
| timestamp | Timestamp for når deployment stoppet |
| target | Objekt som beskriver deployment target (se under) |
| status | Hvordan gikk det? Success, fail osv |
| details | Free form data |
| trigger | Hva som gjorde at deployment ble satt i gang |
| team | Hvilket team eier applikasjonen |

`target` er litt free form, men den har noen definerte felter som skal prøve å beskrive hvor denne eventen hendte.

Jeg tror ikke vi skal kopiere denne direkte, men vi kan se på det som inspirasjon. Identifikatorer (deployment ID, applikasjonsnavn, target feltene, team osv) trenger egentlig en slags global ID standard, i Adevinta er den basert på en URN-aktig greie, slik at man kan partisjonere IDer på en distribuert måte.

**Comment by chriswk** [comment]
En URN som id var jo egentlig ganske behagelig.
Ulempen her er vel kanskje at det blir litt vel spesifikt for deployment.

**Comment by chriswk** [comment]
Så spørsmålet blir om vi skal definere for deployment før vi generaliserer, eller om vi skal ta frustrasjonen ved å definere ett generelt event med en gang

**Comment by chriswk** [comment]
Vi bør ha en ambisjon om å få deployment eventer fra legacy også, ikke bare fra naiserator.

**Comment by chriswk** [comment]
Done with https://github.com/navikt/nada-devrapid-schema
